name: capstone_appdev
description: Sentinel IV-A - Cross-Platform SIEM Visualization and Threat Logging System.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0

  # --- IT 332 Requirements (Backend & Database) ---
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0

  # --- Capstone Enterprise Architecture ---
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
