name: capstone_appdev
description: DICT-4A Wazuh SIEM Hub-and-Spoke dashboard.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.6.12
  flutter_riverpod: ^2.5.1
  firebase_auth: ^5.3.1
  pdf: ^3.13.0
  printing: ^5.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

  

flutter:
  uses-material-design: true
  assets:
    - assets/images/dict_logo.png
    - assets/images/dict_logo_icon.png
    - assets/images/dict_logo_iconpad.png

flutter_launcher_icons:
  android: true
  windows:
    generate: true
    icon_size: 256
  image_path: "assets/images/dict_logo_icon.png"
  adaptive_icon_background: "#0B0F14"
  adaptive_icon_foreground: "assets/images/dict_logo_icon.png"

flutter_native_splash:
  color: "#0B0F14"
  image: assets/images/dict_logo_iconpad.png
  android_12:
    color: "#0B0F14"
    image: assets/images/dict_logo_iconpad.png
  android: true
  ios: true
  web: true