name: capstone_appdev
description: DICT-4A Wazuh SIEM/EDR Hub-and-Spoke dashboard prototype (UI clone).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  flutter_riverpod: ^3.3.2
  firebase_core: ^4.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
