// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcGnbGC-KLH0HaHRdYA9FWzlU2BkfmmTg',
    appId: '1:627426323096:web:4a88116610430128ec3eed',
    messagingSenderId: '627426323096',
    projectId: 'appdev-capstone-integration',
    authDomain: 'appdev-capstone-integration.firebaseapp.com',
    storageBucket: 'appdev-capstone-integration.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC59YLIUqE77csB-gbMmmENfc1CY5M2f10',
    appId: '1:627426323096:android:b6a92b87627f02f1ec3eed',
    messagingSenderId: '627426323096',
    projectId: 'appdev-capstone-integration',
    storageBucket: 'appdev-capstone-integration.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMHIYa0C6TJBkrxKFJa00_f_1EC8SUebk',
    appId: '1:627426323096:ios:7f2555d63f0bb95bec3eed',
    messagingSenderId: '627426323096',
    projectId: 'appdev-capstone-integration',
    storageBucket: 'appdev-capstone-integration.firebasestorage.app',
    iosBundleId: 'com.appdev.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMHIYa0C6TJBkrxKFJa00_f_1EC8SUebk',
    appId: '1:627426323096:ios:7f2555d63f0bb95bec3eed',
    messagingSenderId: '627426323096',
    projectId: 'appdev-capstone-integration',
    storageBucket: 'appdev-capstone-integration.firebasestorage.app',
    iosBundleId: 'com.appdev.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcGnbGC-KLH0HaHRdYA9FWzlU2BkfmmTg',
    appId: '1:627426323096:web:a655e84294d65b65ec3eed',
    messagingSenderId: '627426323096',
    projectId: 'appdev-capstone-integration',
    authDomain: 'appdev-capstone-integration.firebaseapp.com',
    storageBucket: 'appdev-capstone-integration.firebasestorage.app',
  );
}
